- name: install required packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - vim
    - tmux

- template: src=rabbit_nodes.j2 dest=/home/rabbit_ip_from_template.txt mode=0644

