---
# Basic provisioning example
- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Create security group
    local_action:
      module: ec2_group
      name: rabbit_fw
      description: "rabbit_fw"
      region: "{{aws_region}}"
      rules:
        - proto: tcp
          type: ssh
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          type: all
          cidr_ip: 0.0.0.0/0
    register: rabbit_fw 

  - name: Create security group
    local_action:
      module: ec2_group
      name: worker_fw
      description: "worker_fw"
      region: "{{aws_region}}"
      rules:
        - proto: tcp
          type: ssh
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          type: all
          cidr_ip: 0.0.0.0/0
    register: worker_fw

  - debug: var=worker_fw

  - name: create rabbitmq instance
    local_action:
      module: ec2
      key_name: "{{key_name}}"
      region: "{{aws_region}}"
      #group_id: "{{rabbit_fw.group_id}}"
      group: [ "default", "rabbit_fw" ]
      instance_type: "{{instance_type}}"
      instance_tags:
        group: rabbit
      count_tag: 
        group: rabbit
      exact_count: 1
      image: "{{ami_id}}"
      wait: yes
    register: ec2host_rabbit

  - name: setup the internal rabbit ip script for userdata 
    local_action: template src=worker_init_script.j2 dest=/tmp/init_worker.sh
    with_items: ec2host_rabbit.tagged_instances

  - debug: var=ec2host_rabbit

  - add_host: hostname={{ item.public_ip }} groupname=rabbit
    with_items: ec2host_rabbit.tagged_instances

  # Can't combine these for some reason
  - name: wait for rabbit instances to listen on port:22
    wait_for: state=started host={{ item.public_ip }} port=22
    with_items: ec2host_rabbit.tagged_instances

  - name: setup the launch config for the autoscale group for workers with the user_data scripts 
    ec2_lc:
      name: worker_lc
      image_id: "{{ ami_id }}"
      key_name: "{{key_name}}"
      region: "{{aws_region}}"
      security_groups: "default,worker_fw"
      instance_type: "{{ instance_type }}"
      user_data: "{{ lookup('file', '/tmp/init_worker.sh') }}"
    tags: launch_config

  - name: setup the autoscaling group 
    ec2_asg:
      name: worker_asg
      health_check_period: 60
      launch_config_name: worker_lc
      min_size: 1
      max_size: 1
      region: "{{aws_region}}"
    tags: autoscale_group

- name: configure the rabbit
  hosts: rabbit
  remote_user: ubuntu
  sudo: true
  roles:
    - rabbit

#- name: configure the workers
#  hosts: workers
#  remote_user: ubuntu
#  sudo: true
#  roles:
#    - worker

